services:
  db:
    container_name: my_database_container
    image: mongo:6.0
    restart: always
    ports:
    - "27017:27017"
  web:
    container_name: my_web_container
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - .:/myapp
    ports:
    - "3000:3000"
    depends_on:
    - db # This responds to the service name, not the container's name.